---
 - hosts: copinb
   user: devops
   become: yes
   become_method: sudo
   tasks:
     - name: Fetch items from the remote and save it in local
       synchronize:  src={{ item }} dest=/root/patch_folder/october_2022/iTIL-10752/backup/{{ inventory_hostname }}/ mode=pull
       with_items:
         - "/home/{{ inventory_hostname }}/application/resources/views/layout/module/dialer/agentactivity.blade.php"
         - "/home/{{ inventory_hostname }}/application/app/Jobs/ReportLib.php"
